In [1]:
import pandas as pd

In [2]:
import numpy as np
import torch 

## Ways of creating tensors

In [3]:
# direct, dtypes are automatically inferred
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)

In [4]:
# From Numpy
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [5]:
x_np.shape

torch.Size([2, 2])

In [6]:
torch.__version__

'2.0.1'

# Scalar Tensor

In [7]:
scalar = torch.tensor(3)

In [8]:
vector =torch.tensor([1, 3])

In [9]:
tensor = torch.tensor([[[1,2,3,4], 
                        [3,4,6,7],
                        [3,4,6,7]]])

In [10]:
tensor.ndim

3

In [11]:
tensor.shape

torch.Size([1, 3, 4])

In [12]:
tensor_4d = torch.tensor([[[[3,4],
                            [3,4],
                            [3,4]]]])

In [13]:
tensor_4d.shape

torch.Size([1, 1, 3, 2])

In [14]:
if torch.backends.mps.is_available():
    device = "mps"

In [15]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [16]:
tensor = tensor.to(device=device)

In [17]:
tensor

tensor([[0.9273, 0.1973, 0.1813, 0.7115],
        [0.8107, 0.8228, 0.1539, 0.1804],
        [0.5703, 0.3689, 0.8929, 0.3773]], device='mps:0')

In [18]:
t_2 = torch.ones(4, 4)

In [19]:
t_2

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
t_2.shape

torch.Size([4, 4])

In [21]:
t_2.ndim

2

In [22]:
torch.cat([t_2, t_2], dim=1).shape

torch.Size([4, 8])

In [23]:
sales_t = torch.tensor([[[1 , 2, 3], 
                         [3, 6, 9],
                         [2, 4, 5]]])

In [24]:
sales_t.shape

torch.Size([1, 3, 3])

In [25]:
random_tensor = torch.rand(size=(3, 4))

In [26]:
random_tensor

tensor([[0.1850, 0.6328, 0.7226, 0.7319],
        [0.1907, 0.5739, 0.9235, 0.7585],
        [0.9454, 0.7707, 0.5465, 0.5806]])

In [27]:
random_img_tensor = torch.rand(size=(224, 224, 3))

In [28]:
random_img_tensor

tensor([[[0.6431, 0.0765, 0.0339],
         [0.9246, 0.2786, 0.8078],
         [0.3294, 0.9046, 0.5947],
         ...,
         [0.4269, 0.3320, 0.7805],
         [0.1091, 0.9529, 0.6442],
         [0.1068, 0.6774, 0.6213]],

        [[0.6938, 0.5833, 0.4744],
         [0.9803, 0.8215, 0.3489],
         [0.6266, 0.3664, 0.9874],
         ...,
         [0.1789, 0.1607, 0.7580],
         [0.3338, 0.4255, 0.9792],
         [0.3765, 0.9183, 0.1486]],

        [[0.2068, 0.1025, 0.3914],
         [0.5132, 0.4161, 0.5998],
         [0.2787, 0.6049, 0.8086],
         ...,
         [0.7688, 0.0715, 0.0645],
         [0.6141, 0.1900, 0.1747],
         [0.8377, 0.1351, 0.9407]],

        ...,

        [[0.0307, 0.4900, 0.7158],
         [0.0565, 0.5217, 0.8015],
         [0.6815, 0.5815, 0.1144],
         ...,
         [0.3135, 0.9527, 0.0499],
         [0.3261, 0.5884, 0.4216],
         [0.7487, 0.0602, 0.1120]],

        [[0.1747, 0.4804, 0.5358],
         [0.4324, 0.8689, 0.4831],
         [0.

In [29]:
zero_to_ten = torch.arange(start=0, end=10, step=1)

In [30]:
zero_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
tt = torch.zeros_like(random_img_tensor)

In [32]:
tensor = torch.tensor([1,2,3])

In [33]:
tensor + 10

tensor([11, 12, 13])

In [34]:
tensor * tensor

tensor([1, 4, 9])

In [35]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]], dtype=torch.float32)
tensor_B = torch.tensor([[7, 10], 
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [36]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [37]:
tensor_B.T

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])

## Matrix Multiplication

In [38]:
torch.matmul(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [39]:
# 3 * 2 and 3 * 2 #

torch.manual_seed(42)

In [40]:
linear = torch.nn.Linear(in_features=3, out_features=4)

In [41]:
linear(tensor_A.T)

tensor([[1.6293, 0.8116, 3.5593, 1.5407],
        [2.4146, 1.3319, 4.1262, 1.7270]], grad_fn=<AddmmBackward0>)

In [42]:
tensor_A.min()

tensor(1.)

In [43]:
tensor_A.shape

torch.Size([3, 2])

In [44]:
tensor_A

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [45]:
tensor_A.argmax()

tensor(5)

In [46]:
tensor_A[2, 0]

tensor(5.)

In [47]:
x = torch.arange(1., 13)

In [48]:
x

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [49]:
x.reshape(2, 6)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]])

In [50]:
z = x.view(12, 1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [51]:
z[2, 0] = 6

In [52]:
x

tensor([ 1.,  2.,  6.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])

In [53]:
x_stack = torch.stack([x, x, x, x], dim=1)

## Squeeze 

In [54]:
t_ex = torch.arange(1, 13)
t_ex, t_ex.squeeze()

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]))

In [55]:
t_ex_re = t_ex.reshape(3, 4)
t_ex_re_1_d = t_ex.reshape(1, 3, 4)

In [56]:
t_ex_re.shape, t_ex_re_1_d.shape

(torch.Size([3, 4]), torch.Size([1, 3, 4]))

In [57]:
t_ex_re_1_d.squeeze().shape

torch.Size([3, 4])

In [58]:
t_ex_re_1_d.squeeze() == t_ex_re

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Unsqueeze

In [59]:
y = torch.tensor([1, 2, 3, 4])

In [60]:
y_un = y.unsqueeze(dim=0)

In [61]:
y_un.shape

torch.Size([1, 4])

In [62]:
y_un.unsqueeze(dim=1)

tensor([[[1, 2, 3, 4]]])

## Permute

In [63]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

In [64]:
# Permute the original tensor to rearrange the axis order
## Permuting is shifting the dims to axis 0->1, 1->2, 2->0
x_permuted = x_original.permute(2, 0, 1)

In [65]:
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Slicing & Dicing Data

In [66]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [67]:
x[0, :, 2]

tensor([3, 6, 9])

In [68]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [69]:
x[0][0]

tensor([1, 2, 3])

In [70]:
x[0, 0]

tensor([1, 2, 3])

In [71]:
x[0][2][2]

tensor(9)

In [72]:
x[:, 1, 1]

tensor([5])

In [73]:
x[0, 0, :]

tensor([1, 2, 3])

In [74]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [75]:
x = torch.arange(1, 10).reshape(1, 3, 3)

In [76]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [77]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [78]:
x[:, 0]

tensor([[1, 2, 3]])

In [79]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [80]:
x[:, 1, 1]

tensor([5])

In [81]:
torch.manual_seed(seed=42)

In [82]:
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [83]:
torch.manual_seed(seed=42)
torch.rand(3,4)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

In [84]:
import pandas as pd

## Fancy Indexing 

In [85]:
import numpy as np 

In [89]:
X = np.arange(12).reshape((2,2, 3))

In [90]:
X

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [100]:
X[[0,1, 1, 1], [1,1,1, 1]]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [ 9, 10, 11],
       [ 9, 10, 11]])